import type { Item } from '@/components/_organisms/ReaderAbandoned/index';

export const singuratate: Item[] = [
  { kind: 'title', data: 'Singurătate' },
  { kind: 'line', data: 'Cu perdelele lăsate,' },
  { kind: 'line', data: 'Șed la masa mea de brad,' },
  { kind: 'line', data: 'Focul pâlpâie în sobă,' },
  { kind: 'line', data: 'Iară eu pe gânduri cad.' },
  { kind: 'separator' },
  { kind: 'line', data: 'Stoluri, stoluri trec prin minte' },
  { kind: 'line', data: 'Dulci iluzii. Amintiri' },
  { kind: 'line', data: 'Țârâiesc încet ca greeri' },
  { kind: 'line', data: 'Pintre negre, vechi zidiri,' },
  { kind: 'separator' },
  { kind: 'line', data: 'Sau cad grele, mângâioase' },
  { kind: 'line', data: 'Și se sfarmă-n suflet trist,' },
  { kind: 'line', data: 'Cum în picuri cade ceara' },
  { kind: 'line', data: 'La picioarele lui Crist.' },
  { kind: 'separator' },
  { kind: 'line', data: 'În odaie prin unghere' },
  { kind: 'line', data: 'S-a țesut păinjeniș' },
  { kind: 'line', data: 'Și prin cărțile în vravuri' },
  { kind: 'line', data: 'Umblă șoarecii furiș.' },
  { kind: 'separator' },
  { kind: 'line', data: 'În această dulce pace' },
  { kind: 'line', data: 'Îmi ridic privirea-n pod' },
  { kind: 'line', data: 'Și ascult cum învelișul' },
  { kind: 'line', data: 'De la cărți ei mi le rod.' },
  { kind: 'separator' },
  { kind: 'line', data: 'Ah! de câte ori voit-am' },
  { kind: 'line', data: 'Ca să spânzur lira-n cui' },
  { kind: 'line', data: 'Și un capăt poeziei' },
  { kind: 'line', data: 'Și pustiului să pui!' },
  { kind: 'separator' },
  { kind: 'line', data: 'Dar atuncea, greeri, șoareci,' },
  { kind: 'line', data: 'Cu ușor-măruntul mers,' },
  { kind: 'line', data: 'Readuc melancolia-mi,' },
  { kind: 'line', data: 'Iară ea se face vers.' },
  { kind: 'separator' },
  { kind: 'line', data: 'Câteodată... prea arare...' },
  { kind: 'line', data: 'A târziu când arde lampa,' },
  { kind: 'line', data: 'Inima din loc îmi sare' },
  { kind: 'line', data: 'Când aud că sună cleampa...' },
  { kind: 'separator' },
  { kind: 'line', data: 'Este Ea. Deșarta casă' },
  { kind: 'line', data: 'Dintr-o dată-mi pare plină,' },
  { kind: 'line', data: 'În privazul negru-al vieții-mi' },
  { kind: 'line', data: 'E-o icoană de lumină.' },
  { kind: 'separator' },
  { kind: 'line', data: 'Și mi-i ciudă cum de vremea' },
  { kind: 'line', data: 'Să mai treacă se îndură,' },
  { kind: 'line', data: 'Când eu stau șoptind cu draga' },
  { kind: 'line', data: 'Mână-n mână, gură-n gură.' },
  { kind: 'separator' },
  { kind: 'line', data: 'Este Ea. Deșarta casă' },
  { kind: 'line', data: 'Dintr-o dată-mi pare plină,' },
  { kind: 'line', data: 'În privazul negru-al vieții-mi' },
  { kind: 'line', data: 'E-o icoană de lumină.' },
  { kind: 'separator' },
  { kind: 'line', data: 'Și mi-i ciudă cum de vremea' },
  { kind: 'line', data: 'Să mai treacă se îndură,' },
  { kind: 'line', data: 'Când eu stau șoptind cu draga' },
  { kind: 'line', data: 'Mână-n mână, gură-n gură.' },
];
