export function Sidebar() {
  return (
    <div className="flex flex-col  w-80 border border-green-500 bg-yellow-800">
      <div className="flex overflow-auto flex-grow h-0">
        <div className="overflow-auto flex-grow">
          Sidebar
          <br></br>
          Sidebar
          <br></br>
          Sidebar
          <br></br>
          Sidebar
          <br></br>
          Sidebar
          <br></br>
          Sidebar
          <br></br>
          Sidebar
          <br></br>
          Sidebar
          <br></br>
          Sidebar
          <br></br>
          Sidebar
          <br></br>
          Sidebar
          <br></br>
          Sidebar
          <br></br>
          Sidebar
          <br></br>
          Sidebar
          <br></br>
          Sidebar
          <br></br>
          Sidebar
          <br></br>
          Sidebar
          <br></br>
          Sidebar
          <br></br>
          Sidebar
          <br></br>
          Sidebar
          <br></br>
          Sidebar
          <br></br>
          Sidebar
          <br></br>
          Sidebar
          <br></br>
          Sidebar
          <br></br>
          Sidebar
          <br></br>
          Sidebar
          <br></br>
          Sidebar
          <br></br>
          Sidebar
          <br></br>
          Sidebar
          <br></br>
          Sidebar
          <br></br>
          Sidebar
          <br></br>
          Sidebar
          <br></br>
          Sidebar
          <br></br>
          Sidebar
          <br></br>
          Sidebar
          <br></br>
          Sidebar
          <br></br>
          Sidebar
          <br></br>
          Sidebar
          <br></br>
          Sidebar
          <br></br>
          Sidebar
          <br></br>
          Sidebar
          <br></br>
          Sidebar
          <br></br>
          Sidebar
          <br></br>
        </div>
      </div>
    </div>
  );
}
