export function Sidebar() {
  return (
    <div className="flex flex-col border border-green-500 bg-yellow-800 w-[250px] ">
      <div className="overflow-y-scroll h-[500px]">
        Sidebar
        <br></br>
        Sidebar
        <br></br>
        Sidebar
        <br></br>
        Sidebar
        <br></br>
        Sidebar
        <br></br>
        Sidebar
        <br></br>
        Sidebar
        <br></br>
        Sidebar
        <br></br>
        Sidebar
        <br></br>
        Sidebar
        <br></br>
        Sidebar
        <br></br>
        Sidebar
        <br></br>
        Sidebar
        <br></br>
        Sidebar
        <br></br>
        Sidebar
        <br></br>
        Sidebar
        <br></br>
        Sidebar
        <br></br>
        Sidebar
        <br></br>
        Sidebar
        <br></br>
        Sidebar
        <br></br>
        Sidebar
        <br></br>
        Sidebar
        <br></br>
        Sidebar
        <br></br>
        Sidebar
        <br></br>
        Sidebar
        <br></br>
        Sidebar
        <br></br>
        Sidebar
        <br></br>
        Sidebar
        <br></br>
        Sidebar
        <br></br>
        Sidebar
        <br></br>
        Sidebar
        <br></br>
        Sidebar
        <br></br>
        Sidebar
        <br></br>
        Sidebar
        <br></br>
        Sidebar
        <br></br>
        Sidebar
        <br></br>
        Sidebar
        <br></br>
        Sidebar
        <br></br>
        Sidebar
        <br></br>
        Sidebar
        <br></br>
        Sidebar
        <br></br>
        Sidebar
        <br></br>
        Sidebar
        <br></br>
      </div>
    </div>
  );
}
